// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh7lZVHM9JcpuhBdxsac6anxctwJ22rO4',
    appId: '1:53361383199:web:afbc1a3730f1293931022a',
    messagingSenderId: '53361383199',
    projectId: 'usersdb-4d55a',
    authDomain: 'usersdb-4d55a.firebaseapp.com',
    databaseURL: 'https://usersdb-4d55a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'usersdb-4d55a.appspot.com',
    measurementId: 'G-0HWP4FW7W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLTNd6IUYNtRVjhgoPsyRSPEorCWQVSMk',
    appId: '1:53361383199:android:a400bce64f4fdc2531022a',
    messagingSenderId: '53361383199',
    projectId: 'usersdb-4d55a',
    databaseURL: 'https://usersdb-4d55a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'usersdb-4d55a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA9QO8tyYwNL1BGoraK0eEacikWzxzKn4',
    appId: '1:53361383199:ios:134341b991446e7e31022a',
    messagingSenderId: '53361383199',
    projectId: 'usersdb-4d55a',
    databaseURL: 'https://usersdb-4d55a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'usersdb-4d55a.appspot.com',
    iosClientId: '53361383199-d6o6gptj9ejcne3gvlk46ovi963fomse.apps.googleusercontent.com',
    iosBundleId: 'com.example.usersManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA9QO8tyYwNL1BGoraK0eEacikWzxzKn4',
    appId: '1:53361383199:ios:134341b991446e7e31022a',
    messagingSenderId: '53361383199',
    projectId: 'usersdb-4d55a',
    databaseURL: 'https://usersdb-4d55a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'usersdb-4d55a.appspot.com',
    iosClientId: '53361383199-d6o6gptj9ejcne3gvlk46ovi963fomse.apps.googleusercontent.com',
    iosBundleId: 'com.example.usersManagement',
  );
}
